// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":false,"description":"Plugin Analysis Common Base","parameters":{}},
{"name":"ExtraWindow","status":false,"description":"Extra Window Display Per Scene Plugin","parameters":{"WindowList":"[]"}},
{"name":"TextPicture","status":false,"description":"Displays text as a picture.","parameters":{}},
{"name":"ButtonPicture","status":false,"description":"Makes a picture clickable.","parameters":{}},
{"name":"TL_AutoSave","status":false,"description":"","parameters":{}}
];
